#!/bin/bash

PWD=$(pwd)

git clone https://github.com/pusher/oauth2_proxy.git $PWD/contrib/oauth2_proxy

cd $PWD/contrib/oauth2_proxy

git apply $PWD/files/provider_authsch.patch

docker build -f Dockerfile -t $IMAGE_NAME .