#!/bin/bash

ORIG_PWD=$(pwd)

git clone https://github.com/pusher/oauth2_proxy.git $ORIG_PWD/contrib/oauth2_proxy

cd $ORIG_PWD/contrib/oauth2_proxy

git apply $ORIG_PWD/files/provider_authsch.patch

docker build -f Dockerfile -t $IMAGE_NAME .